name: Learn

# event are being created
on:
  push:
    branches: [main]

jobs:
  setup_django_projects:
    runs-on: ubuntu-lastest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:    
      - name: checkout code
        uses: actions/checkout@v6
      - name: setup python $ {{matrix.pyhton-version}}
        uses: actions/setup-python@v6
        with:
          python-version: $ {{matrix.python-version}}
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run tests
        run: python manage.py tests 
